## Creating Array

In [24]:
from array import array
arr = array('i', (i for i in range(1, 6)))
arr

array('i', [1, 2, 3, 4, 5])

In [26]:
type(arr)

array.array

In [27]:
arr.typecode

'i'

## Slicing

In [29]:
arr[1:3]

array('i', [2, 3])

In [21]:
from array import array
array2d = [array('i', (i*j for i in range(1,4))) for j in range(1,3)]

In [34]:
array2d

[array('i', [1, 2, 3]), array('i', [2, 4, 6])]

In [25]:
(i*j for i in range(1,4)) for j in range(1,3)

SyntaxError: invalid syntax (2240023713.py, line 1)

In [32]:
from array import array
arr = array('i', [1, 2, 3, 1, 4, 7, 9, 12])
print(arr[1:4])
print(arr[1:4][1])

array('i', [2, 3, 1])
3


In [33]:
for i in range(3):
    print(i)

0
1
2


In [35]:
from array import array
array2d = [array('f', ((i+5)/(j-3) for i in range(3))) for j in range(3)]
c = 0
for i in range(3):
    for j in range(3):
        if array2d[i][j] <= -3:
            c += 1

In [36]:
c

5

In [66]:
def char_count(arr):
    '''
    input:
    arr -> the input character array
    
    output:
    consonant_count -> the number of unique consonants present in the character array
    '''
    consonant_count = 0

    
    # Your code starts here
    vowels = ['a', 'e', 'i', 'o', 'u']
    consonant = set()    
    
    for i in range(len(arr)):
        if(arr[i] not in vowels and arr[i] != ' '):
            print(arr[i])
            consonant.add(arr[i])
            
    consonant_count = len(consonant)
    print(consonant)
    
    # Your code ends here
    return consonant_count

In [67]:
char_count('a b d e a g o i e j l h s d k f l w i d j w l k e j')

b
d
g
j
l
h
s
d
k
f
l
w
d
j
w
l
k
j
{'b', 'j', 'd', 'w', 'f', 'k', 'l', 's', 'g', 'h'}


10

In [73]:
from array import array
arr= array("i",[2,1,3,4,7,6,4,6,9])
for i in range(len(arr)+1):
    if arr[i] in arr[i+1:]:
        print(arr[i], " ", arr[i+1:])
        break

4   array('i', [7, 6, 4, 6, 9])


In [85]:
from array import array

X= [array("i",[2,1,49,8,0]),
 array("i",[11,24,4,65,5])]
X

result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
result
# t=[]
# transpose= [x for x in result]
# print(transpose)


[[2, 11], [1, 24], [49, 4], [8, 65], [0, 5]]

In [87]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [88]:
arr1=np.array(['Ram','Astha','Brahat'])
arr2=np.array(['Shyam','Kalyan','Naveen'])
arr1>arr2

array([False, False, False])

In [89]:
import numpy as np
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
X.max(axis=1)

array([ 3,  7, 11])

In [96]:
X.T.max(axis=0)

array([ 3,  7, 11])

In [97]:
X.sum()

66

In [100]:
[i for i in X]

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [101]:
import numpy as np
def sort_marks(arr2d, j):
    '''Input: arr2d= a 2d python list.
              j= integer representing the number of quiz according to which the marks need to be sorted.
        Output: a 2d numpy array.'''

    # Make sure that you are returning the output matrix simply inside this function.
    
    
    ans = None
    # YOUR CODE GOES HERE
    
    
    return ans

In [126]:
import numpy as np

def update_height(height,delta):
    height = np.array(height)
    delta = np.array(delta)
    new_height = height+delta 
    return new_height

In [127]:
update_height([1, 2, 3, 5, 6, 7], [1, 2, 3, 1, 2, 3])

array([ 2,  4,  6,  6,  8, 10])

In [128]:
def update_height(height, delta):
    new_height=[]
    for i in range(len(height)):
        new_height.append(height[i]+delta[i])
    return new_height

In [129]:
update_height([1, 2, 3, 5, 6, 7], [1, 2, 3, 1, 2, 3])

[2, 4, 6, 6, 8, 10]

In [130]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

1.0


In [132]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p+q)) 

[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [144]:
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis]])


[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [156]:
import numpy as np
def seq(start, length, step):
    ''' start, length and step are in form of integers all representing the attributes as their names suggest
        output -> A numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    result = np.arange(start, start + ( length * step), step)
    return result

In [157]:
np.arange(5, 5 + ( 10 * 3), 3)
# np.linspace(5, 5 + (10 * 3), 3, dtype='int')

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [158]:
seq(5, 10, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [159]:
a = np.zeros(27).reshape(3, 3, 3)
b = np.arange(9).reshape(3, 3)
a + b

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [160]:
a + b[np.newaxis, :, :]

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [161]:
b + a[np.newaxis, :, :]

array([[[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]],

        [[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]],

        [[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]]])

In [162]:
a + b[:, np.newaxis, :]

array([[[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]],

       [[3., 4., 5.],
        [3., 4., 5.],
        [3., 4., 5.]],

       [[6., 7., 8.],
        [6., 7., 8.],
        [6., 7., 8.]]])