In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("gapminder.csv")
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [6]:
df.sort_values(by=["year", "life_exp"], ascending=[False, True])

country  year  population continent  life_exp       gdp_cap
1463     Swaziland  2007     1133066    Africa    39.613   4513.480643
1043    Mozambique  2007    19951656    Africa    42.082    823.685621
1691        Zambia  2007    11746035    Africa    42.384   1271.211593
1355  Sierra Leone  2007     6144562    Africa    42.568    862.540756
887        Lesotho  2007     2012649    Africa    42.592   1569.331442
...            ...   ...         ...       ...       ...           ...
408        Denmark  1952     4334000    Europe    70.780   9692.385245
1464        Sweden  1952     7124673    Europe    71.860   8527.844662
1080   Netherlands  1952    10381988    Europe    72.130   8941.571858
684        Iceland  1952      147962    Europe    72.490   7267.688428
1140        Norway  1952     3327728    Europe    72.670  10095.421720

[1704 rows x 6 columns]

In [12]:
ser = pd.Series([1, 10, 100, 100])
ser

0      1
1     10
2    100
3    100
dtype: int64

In [9]:
arr = np.arange(20).reshape(5, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
temp = pd.DataFrame(arr)
temp

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [41]:
import numpy as np
def rotate_img(mat):
    '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    rows = len(mat)
    for i in range(len(mat[0])):
        t = mat[0][i]
        mat[0][i] = mat[rows-1][i]
        mat[rows-1][i] = t    
    return np.array(mat).T
    

In [43]:
 arr = [[1, 2, 3], 
  [4, 5, 6],
  [7, 8, 9]]

arr = [[1],[2]]

rotate_img(arr)

2


array([[2, 1]])

In [45]:

arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])


arr1= np.array([[2,2,2,2]])
def func(x,y):
    return x*y

vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [46]:
arr1= 2   
def func(x,y):
    return x*y

vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [47]:
arr1= np.array([[2],[2],[2],[2]])
    
def func(x,y):
    return x*y

vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])