In [1]:
import numpy as np

## Brodcasting

In [4]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

#### tile

In [11]:
np.tile(a, (3, 1)) # repeat array a 3 times in row wise and 1 time in column wise

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [12]:
np.tile(a, (3, 2))  # repeat array a 3 times in row wise and 2 time in column wise

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

## Array spliting and Stacking

In [17]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.split(arr, 2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [21]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.split(arr1, 2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [19]:
np.split(arr, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [20]:
np.split(arr, [3, 5, 7])

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([ 7,  8,  9, 10, 11])]

### HSplit & VSplit

In [25]:
marr = np.arange(16).reshape(4, 4)
marr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
marr.shape

(4, 4)

In [27]:
np.hsplit(marr, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [29]:
np.vsplit(marr, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [31]:
np.hsplit(marr, [1, 3, 5])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int32)]

In [32]:
np.vsplit(marr, [1, 3, 5])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int32)]

#### split & Axis

In [34]:
np.split(marr, [1, 3, 5], axis = 0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int32)]

In [35]:
np.split(marr, [1, 3, 5], axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int32)]

#### VStack & HStack

In [36]:
arr1 = np.arange(6).reshape(2, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
arr2 = np.arange(10, 12).reshape(2, 1)
arr2

array([[10],
       [11]])

In [39]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 11]])

In [40]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
arr3 = np.arange(10, 16).reshape(2, 3)
arr3

array([[10, 11, 12],
       [13, 14, 15]])

In [43]:
np.vstack((arr1, arr3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

#### Concatination

In [45]:
a = np.arange(3).reshape(3, 1)
a

array([[0],
       [1],
       [2]])

In [46]:
np.concatenate((a, a, a), axis=0)

array([[0],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [2]])

In [47]:
np.concatenate((a, a, a), axis=1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [48]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [49]:
b = np.arange(5, 7).reshape(1, 2)
b

array([[5, 6]])

In [50]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [52]:
np.concatenate((a, b.T), axis=None)

#axis : int, optional The axis along which the arrays will be joined.  If axis is None,
    #arrays are flattened before use.  Default is 0.

array([1, 2, 3, 4, 5, 6])