In [1]:
import numpy as np

## Creating array using numpy

#### Option1 - Creating array using numpy array and finding square

In [8]:
a = [1, 2, 3, 4, 5]

In [3]:
type(a)

list

In [4]:
arr = np.array(a)
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr ** 2

array([ 1,  4,  9, 16, 25])

#### adding number with numpy array

In [7]:
arr + 1

array([2, 3, 4, 5, 6])

#### Option2 - Creating array using numpy arange

In [10]:
l = list(range(1000000))

In [11]:
%timeit [i ** 2 for i in l]

402 ms ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
arr = np.arange(1000000) # np.arange(start - 0 (default), end, step)

In [13]:
%timeit arr ** 2

2 ms ± 74.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Numpy array too faster than array
#### operations can be applied direclt on numpy array

In [14]:
type(arr)

numpy.ndarray

In [19]:
# attributes of numpy array

arr.ndim

1

In [20]:
arr.shape

(1000000,)

In [21]:
type(arr.shape)

tuple

#### Option3 - np.linspace - Linear space

In [22]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## 2D Array

In [23]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.ndim

2

In [27]:
arr.shape

(3, 3)

## Reshape

##### Number of elements before and after reshape should be same

In [28]:
m1 = np.arange(1, 13)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
m2 = m1.reshape(3, 4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Flatten & Ravel used to flatten the multi-dimension to single dimension

In [30]:
m2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
m2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
m2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Transpose

In [38]:
arr = np.array([[1,2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [40]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.transpose(arr)

array([[1, 3, 5],
       [2, 4, 6]])

In [45]:
arr1 = np.arange(1, 5)
arr1
# 1D array

array([1, 2, 3, 4])

In [53]:
arr1.T
# it is not changing anything, since it is 1D vector

array([1, 2, 3, 4])

In [50]:
arr1.reshape(1, 4)
# 2D array

array([[1, 2, 3, 4]])

In [52]:
arr1.reshape(1, 4).T

array([[1],
       [2],
       [3],
       [4]])

### -1 instead of row/column

In [54]:
A = np.arange(1, 13)

In [55]:
A.reshape (-1, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [58]:
A.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### Special Arrays

In [59]:
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(shape = (5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [63]:
np.zeros(shape = (5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.zeros(shape = (5, 5, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [67]:
np.ones(1)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [68]:
np.ones(shape = (5, 5, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [69]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Slicing & Indexing

In [85]:
m1 = np.arange(4, 16)
m1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
m1[7]

11

In [87]:
m1[-2]

14

In [88]:
m1[6:10]

array([10, 11, 12, 13])

In [89]:
m1[6:-1]

array([10, 11, 12, 13, 14])

In [90]:
m1[6:]

array([10, 11, 12, 13, 14, 15])

In [91]:
m2 = m1.reshape(3, 4) 
m2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
m2[2,2]

14

In [95]:
m2[2]

array([12, 13, 14, 15])

In [96]:
m2[1, -1]

11

In [97]:
m2[1, 3]

11

In [103]:
m2[1:,1:-1]

array([[ 9, 10],
       [13, 14]])

In [104]:
arr = np.arange(5, 25).reshape(4, 5)
arr

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
arr[1:, 0:2]

array([[10, 11],
       [15, 16],
       [20, 21]])

In [108]:
arr[1:, :2]

array([[10, 11],
       [15, 16],
       [20, 21]])

### Replacing values

In [109]:
m2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### How to change 15 to 100?

In [111]:
m2[2:, 3:] = 100

In [113]:
m2

array([[  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 100]])

In [114]:
m2[-1,-1] = 200
m2

array([[  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 200]])

In [116]:
a = [1, 2, 3, 4, 5]
b = [8, 7, 6]

In [120]:
a[2:] = b[::-1]
a

[1, 2, 6, 7, 8]

In [123]:
b[::-1]

[6, 7, 8]