In [3]:
import numpy as np

In [4]:
data = np.loadtxt('fitness.txt', dtype='str')

In [5]:
data[:5]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

In [14]:
stepCounts = data[:, 1].astype('float')
stepCounts

array([5464., 6041.,   25., 5461., 6915., 4545., 4340., 1230.,   61.,
       1258., 3148., 4687., 4732., 3519., 1580., 2822.,  181., 3158.,
       4383., 3881., 4037.,  202.,  292.,  330., 2209., 4550., 4435.,
       4779., 1831., 2255.,  539., 5464., 6041., 4068., 4683., 4033.,
       6314.,  614., 3149., 4005., 4880., 4136.,  705.,  570.,  269.,
       4275., 5999., 4421., 6930., 5195.,  546.,  493.,  995., 1163.,
       6676., 3608.,  774., 1421., 4064., 2725., 5934., 1867., 3721.,
       2374., 2909., 1648.,  799., 7102., 3941., 7422.,  437., 1231.,
       1696., 4921.,  221., 6500., 3575., 4061.,  651.,  753.,  518.,
       5537., 4108., 5376., 3066.,  177.,   36.,  299., 1447., 2599.,
        702.,  133.,  153.,  500., 2127., 2203.])

In [15]:
np.mean(stepCounts)

2935.9375

In [16]:
stepCounts.min()

25.0

In [19]:
 stepCounts.max()

7422.0

In [36]:
temp = data
temp.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [37]:
date, step_count, mood, calories, hours_of_sleep, activity_status, weight = temp.T

In [38]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [39]:
hours_of_sleep

array(['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
       '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
       '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
       '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
       '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
       '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
       '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
       '2', '8', '5', '5', '5'], dtype='<U10')

In [40]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [43]:
mood[mood == '100'] = 'Sad'
mood[mood == '200'] = 'Normal'
mood[mood == '300'] = 'Happy'

In [45]:
mood

array(['Normal', 'sad', 'sad', 'sad', 'Normal', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', 'sad', 'Happy', 'sad', 'sad', 'sad', 'sad',
       'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal',
       'Happy', 'Normal', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Normal', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Normal',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Normal', 'sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'sad', 'Normal', 'Normal',
       'sad', 'sad', 'Normal', 'Normal', 'Happy', 'Normal', 'Normal',
       'sad', 'Normal', 'sad', 'Normal', 'Normal', 'sad', 'sad', 'sad',
       'sad', 'Happy', 'Normal', 'Happy', 'Normal', 'sad', 'sad', 'sad',
       'Normal', 'Normal', 'sad', 'sad', 'Happy', 'Normal', 'Normal',
       'Happy'], dtype='<U10')

In [48]:
a = np.random.randint(1, 10, size=(4, 3))
a

array([[6, 1, 1],
       [2, 7, 6],
       [3, 8, 7],
       [4, 4, 1]])

In [51]:
np.sort(a, axis=0)

array([[2, 1, 1],
       [3, 4, 1],
       [4, 7, 6],
       [6, 8, 7]])

## Sort in reverse order

In [55]:
a = np.array([6, 2, 5, 9, 10, 3])
a

array([ 6,  2,  5,  9, 10,  3])

In [56]:
np.sort(a)

array([ 2,  3,  5,  6,  9, 10])

In [57]:
np.sort(-a)

array([-10,  -9,  -6,  -5,  -3,  -2])

In [58]:
-np.sort(-a)

array([10,  9,  6,  5,  3,  2])

In [59]:
np.sort(a)[::-1]

array([10,  9,  6,  5,  3,  2])

In [61]:
a = np.array([6, 2, 5, 9, 10, 3])

array([ 6,  2,  5,  9, 10,  3])

In [62]:
import math

In [64]:
math.log(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [66]:
arr = np.random.randint(2, 7, size=(3, 3))
arr

array([[4, 4, 5],
       [5, 4, 2],
       [4, 4, 6]])

In [68]:
math.factorial(arr)

TypeError: only integer scalar arrays can be converted to a scalar index

In [69]:
fact = np.vectorize(math.factorial)

In [70]:
fact(arr)

array([[ 24,  24, 120],
       [120,  24,   2],
       [ 24,  24, 720]])