In [1]:
import numpy as np

## Q1

In [3]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])


In [4]:
A + 1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [5]:
[x+1 for x in A]

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [6]:
list(map(lambda x:x+1, A))

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [9]:
A+"1"

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int32'), dtype('<U1')) -> None

In [11]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Q2

In [12]:
a = np.array([[[ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0]],
[[ 0, 0, 255],
 [255, 255, 255],
 [ 0, 0, 0],
 [255, 0, 0]]])

In [26]:
a

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [255,   0,   0]]])

In [30]:
a[1]

array([[  0,   0, 255],
       [255, 255, 255],
       [  0,   0,   0],
       [255,   0,   0]])

In [31]:
b = np.array([255, 0, 255])

In [32]:
c = np.all(a == b, axis = 1) 

In [33]:
c

array([[False,  True, False],
       [False, False, False]])

## Q3

In [35]:
import numpy as np

In [48]:
arr = 2 * np.arange(0, 2, 0.5)
if (arr <= 0.6):
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Q4

In [61]:
import math

In [107]:
a = np.array([[ 7, 4, 8, 5, 1],  
 [ 8, 0, 11, 3, 5],  
 [ 9, 6, 3, 5, 0],  
 [ 1, 5, 7, 3, 2],  
 [ 4, 7, 2, 9, 1]])
a

array([[ 7,  4,  8,  5,  1],
       [ 8,  0, 11,  3,  5],
       [ 9,  6,  3,  5,  0],
       [ 1,  5,  7,  3,  2],
       [ 4,  7,  2,  9,  1]])

In [116]:
a[:2,:2] #[start:end, start:end]

array([[7, 4],
       [8, 0]])

In [120]:
a[:2][:2]

array([[ 7,  4,  8,  5,  1],
       [ 8,  0, 11,  3,  5]])

In [68]:
a = np.array([[1,1,2],[4,6,8]])
a

array([[1, 1, 2],
       [4, 6, 8]])

In [74]:
def new_mat(mat):
    '''mat -> A 2d numpy array
       Output -> A 2d numpy array is expected to be returned'''
    # YOUR CODE GOES HERE
    mask = mat % 2 == 0
    result = mat[mask]
    return result.reshape( int(math.sqrt(len(result))), int(math.sqrt(len(result))))

In [75]:
new_mat(a)

array([[2, 4],
       [6, 8]])

## Q5 One hot encoding

In [176]:
def onehot(arr):

    """
        Input arr is numpy array here
        Output an array of dimension (arr.size, max(array)+1)
    """
    result=None    
    b = np.zeros((arr.size, arr.max() + 1))
    b[np.arange(arr.size), arr] = 1
    result = b.astype(int)
    return result

In [177]:
onehot(np.array([1, 2, 3, 4]))

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [186]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [187]:
np.arange(arr1.size)

array([0, 1, 2, 3])

In [188]:
b = np.zeros((4, 5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [189]:
b[np.arange(arr1.size), arr1] = 1
# b[[0, 1, 2, 3], [1, 2, 3, 4]] = 1
b

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Q6 Sort in reverse order

In [123]:
a = np.array([6, 2, 5, 9, 10, 3])
a

array([ 6,  2,  5,  9, 10,  3])

In [124]:
np.sort(a)[:]

array([ 2,  3,  5,  6,  9, 10])

In [125]:
np.sort(a)[:-1]

array([2, 3, 5, 6, 9])

In [126]:
np.sort(a)[::1]

array([ 2,  3,  5,  6,  9, 10])

In [127]:
np.sort(a)[::-1] #[start element:end elment: step size]

array([10,  9,  6,  5,  3,  2])

#### Other option

In [128]:
-np.sort(-a)

array([10,  9,  6,  5,  3,  2])

## Sorting (2D)Matrix (jth column) 

In [190]:
import numpy as np
def sort_marks(arr2d, j):
    '''Input: arr2d= a 2d python list.
              j= integer representing the number of quiz according to which the marks need to be sorted.
        Output: a 2d numpy array.'''

    # Make sure that you are returning the output matrix simply inside this function.
    
    
    ans = None
    # YOUR CODE GOES HERE
    ans = arr2d[arr2d[:, j].argsort()]
    print(ans)
    return ans


In [191]:
a = np.array([[ 7, 4, 8],  
 [ 8, 0, 11],  
 [ 9, 6, 3]])
a

array([[ 7,  4,  8],
       [ 8,  0, 11],
       [ 9,  6,  3]])

In [203]:
type(sort_marks(a, 2))

[[ 9  6  3]
 [ 7  4  8]
 [ 8  0 11]]


numpy.ndarray

In [200]:
a

array([[ 7,  4,  8],
       [ 8,  0, 11],
       [ 9,  6,  3]])

In [198]:
a[:, 1].argsort()

array([1, 0, 2], dtype=int64)

In [201]:
a[:, 2].argsort()

array([2, 0, 1], dtype=int64)

In [202]:
a[a[:, 2].argsort()]

array([[ 9,  6,  3],
       [ 7,  4,  8],
       [ 8,  0, 11]])

In [157]:
a[a[:, 1].argsort()]  # sort by day

array([[ 8,  0, 11],
       [ 7,  4,  8],
       [ 9,  6,  3]])

In [147]:
b = np.array([[5, 3, 9],
[2, 1, 4],
[7, 6, 8]])
b

array([[5, 3, 9],
       [2, 1, 4],
       [7, 6, 8]])

In [150]:
sort_marks(b, 3)

array([[2, 1, 4],
       [7, 6, 8],
       [5, 3, 9]])

## Q7. Python broadcasting

In [204]:
import numpy as np
a = np.zeros(27).reshape(3, 3, 3)
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [205]:
b = np.arange(9).reshape(3, 3) 
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [206]:
a + b[np.newaxis, :, :]

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [207]:
b + a[np.newaxis, :, :]

array([[[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]],

        [[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]],

        [[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]]])

In [208]:
a + b[:, np.newaxis, :]

array([[[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]],

       [[3., 4., 5.],
        [3., 4., 5.],
        [3., 4., 5.]],

       [[6., 7., 8.],
        [6., 7., 8.],
        [6., 7., 8.]]])

In [209]:
a + b[:, :, np.newaxis]

array([[[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.]],

       [[6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.]]])

## Q16. Mean Squared Error (MSE)