In [1]:
import numpy as np

## Masking/Fancy Indexing

In [3]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [5]:
(m1 < 6).sum()

6

In [7]:
mask = m1 < 6
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [8]:
m1[mask]

array([0, 1, 2, 3, 4, 5])

In [6]:
(m1 % 2 == 0)

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [10]:
mask1 = m1 % 2 == 0
mask1

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [11]:
m1[mask1]

array([ 0,  2,  4,  6,  8, 10])

## Multiple Conditions

In [12]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# Get the element devisible by 2 or 5

(m1 % 2 == 0) | (m1 % 5 == 0)


array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [ True, False,  True, False]])

#### Question

In [20]:
a = np.array([0, 1, 2, 3, 4, 5])
mask = (a % 2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [21]:
a[1:4] = [10, 20, 30]
a

array([-1, 10, 20, 30, -1,  5])

## uFunc -> universal Functions

- sum
- mean
- sort
- min
- max
- std
- log
- exp
- median


#### Sum

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [25]:
a + b

array([ 6,  8, 10, 12])

In [26]:
arr = np.random.randint(1, 5, size=(3, 4))
arr

array([[3, 1, 2, 3],
       [3, 4, 2, 1],
       [1, 3, 1, 1]])

In [27]:
np.sum(arr)

25

In [28]:
arr.sum()

25

#### reshape

In [29]:
arr.reshape(2, 6)

array([[3, 1, 2, 3, 3, 4],
       [2, 1, 1, 3, 1, 1]])

In [30]:
np.reshape(arr, (2, 6))

array([[3, 1, 2, 3, 3, 4],
       [2, 1, 1, 3, 1, 1]])

#### Sum across column/row

In [31]:
arr

array([[3, 1, 2, 3],
       [3, 4, 2, 1],
       [1, 3, 1, 1]])

In [32]:
np.sum(arr, axis=0)

array([7, 8, 5, 5])

In [33]:
np.sum(arr, axis=1)

array([ 9, 10,  6])

In [34]:
np.mean(arr, axis= 0)

array([2.33333333, 2.66666667, 1.66666667, 1.66666667])

In [35]:
np.mean(arr, axis= 1)

array([2.25, 2.5 , 1.5 ])

#### Any vs All

In [36]:
a = np.array([True, True, False])
np.any(a)

True

In [37]:
a = np.array([1, 2, 3, 4])
np.any(a)

True

In [38]:
a = np.array([0, 0, 0, 0, -1])
np.any(a)

True

In [39]:
a = np.zeros(5)
np.any(a)

False

In [40]:
a = np.arange(1, 5)
b  = np.arange(4, 0, -1)

In [41]:
a, b

(array([1, 2, 3, 4]), array([4, 3, 2, 1]))

In [42]:
a > b

array([False, False,  True,  True])

In [43]:
np.any(a > b)

True

In [44]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

#### np.sort()

In [45]:
a = np.random.randint(1, 15, size=(5,))
a

array([13,  1, 14,  8,  2])

In [46]:
np.sort(a)

array([ 1,  2,  8, 13, 14])

In [47]:
a

array([13,  1, 14,  8,  2])

In [49]:
a = np.array([2, 30, 41, 7, 17, 52])
a

array([ 2, 30, 41,  7, 17, 52])

In [50]:
np.argsort(a)

array([0, 3, 4, 1, 2, 5], dtype=int64)

In [51]:
a = np.array([1, 5, 8, 2, 0])

In [54]:
np.ndarray.sort(a)
a

array([0, 1, 2, 5, 8])

## Vectorization

##### Performing any kind of operation on Vectors (1D)/ Array (2D, 3D, ...). Operations might be arithmetic, logic or any function

In [55]:
pA = np.array([5, 4, 1, -3])
pB = np.array([6, 2, 3, 8])

In [56]:
pA - pB

array([ -1,   2,  -2, -11])

In [57]:
np.sqrt(np.sum(np.square(pA- pB)))

11.40175425099138

## Matrix Multiplication

In [60]:
a = np.random.randint(1, 9, size=(3, 3))
a

array([[6, 5, 3],
       [7, 3, 4],
       [6, 3, 1]])

In [61]:
b = np.random.randint(1, 9, size=(3, 3))
b

array([[5, 2, 2],
       [6, 4, 5],
       [5, 3, 3]])

In [62]:
a @ b

array([[75, 41, 46],
       [73, 38, 41],
       [53, 27, 30]])

#### other options

In [63]:
np.matmul(a, b)

array([[75, 41, 46],
       [73, 38, 41],
       [53, 27, 30]])

In [64]:
np.dot(a, b)

array([[75, 41, 46],
       [73, 38, 41],
       [53, 27, 30]])